### ISSUE TITLE
Application.Current.Dispatcher.Invoke(new Action(() =>

### ISSUE THREAD

**Issue by vanlion84** [johnpierson/DynamoSampleWPFWindow#1]
This part "Application.Current.Dispatcher.Invoke(new Action(() =>{})); will give you an error "Object reference not set to an instance of an object" removing it will solve te error. But has this something to do that the wpf form get's modeless?

**Comment by johnpierson** [comment]
Yes. That invokes this on the Ui thread as dynamo sandbox is multithreaded.

**Comment by vanlion84** [comment]
oke I'd like to get it modeless so how did you handle "Object reference not set to an instance of an object" in your script?

**Comment by johnpierson** [comment]
Oh, this is not for a modeless form. That would take a different strategy. Sorry about that.

**Comment by vanlion84** [comment]
Ok! i know the stragety for building modeless forms with C# addins but when i trie to implement the same technique in a dynamo  node the form stays open and the script is already finished in the background. So i was hoping that rule has something to deal with it...but it's not

**Comment by johnpierson** [comment]
Yeah, me too. One of my long-time goals is to get that working. Very similar to how HumanUI works with grasshopper.

**Comment by vanlion84** [comment]
Yes it would be so nice if you can control that. I will keep searching for a solution...
